class Contract(Base):
    __tablename__ = "contract"
    contract_id = Column(String(50), primary_key=True)
    customer_id = Column(String(50), ForeignKey("customer.customer_id"))
    staff_id = Column(String(50), ForeignKey("staff.staff_id"))
    contract_type_id = Column(String(50), ForeignKey("contract_type.contract_type_id"))
    incoterm_id = Column(String(50), ForeignKey("incoterm.incoterm_id"))
    payment_term_id = Column(String(50), ForeignKey("payment_term.payment_term_id"))
    proforma_invoice_id = Column(String(50), ForeignKey("proforma_invoice.proforma_invoice_id"))
    contract_date = Column(DateTime)
    effective_date = Column(DateTime)
    expiry_date = Column(DateTime)
    total_contract_value = Column(Float)
    total_quantity = Column(Float)
    currency = Column(String(10))
    loading_port = Column(String(255))
    destination_port = Column(String(255))
    status = Column(String(20))
    signed_date = Column(DateTime)